### ISSUE TITLE
Add coverage reports using `pytest-cov`

### ISSUE THREAD

**Issue by gridhead** [t0xic0der/nvidia-auto-installer-for-fedora-linux#119]
We would want to know how much part of the code is tested.

**Comment by aitorres** [comment]
Hi! I added a PR that addresses this issue (see #121), let me know if there's anything else I could add!

**Comment by onuralpszr** [comment]
Complete via : https://github.com/t0xic0der/nvidia-auto-installer-for-fedora-linux/commit/11e81df107fe31f6612946df2be44ab2a07b3efd
