### ISSUE TITLE
Automate monitoring status of akmod transaction

### ISSUE THREAD

**Issue by gridhead** [t0xic0der/nvidia-auto-installer-for-fedora-linux#12]
Reduce the mandatory sleep time while doing so.

![Screenshot from 2020-05-23 07-56-58](https://user-images.githubusercontent.com/49605954/82721235-ff668800-9cd8-11ea-9250-8ee38b2e543e.png)

**Comment by ferdnyc** [comment]
As I noted in [my comment here](https://github.com/t0xic0der/nvidia-auto-installer-for-fedora-ws/commit/a9c58997d65ee7eeaad89c2628d296910d48ed83#commitcomment-39430748), I'm not convinced this is necessary at all.

**Comment by onuralpszr** [comment]
https://github.com/t0xic0der/nvidia-auto-installer-for-fedora-linux/commit/a9c58997d65ee7eeaad89c2628d296910d48ed83#commitcomment-96207804 

Solved by rpmfusion/akmod
