### ISSUE TITLE
problem on 0-nvidia.rules

### ISSUE THREAD

**Issue by fabiopesaju** [t0xic0der/nvidia-auto-installer-for-fedora-linux#193]
hi. First, congratulations on the project.

![image](https://user-images.githubusercontent.com/20627847/220408957-bb37ca6e-909f-44b5-a5a8-d96be30de856.png)
im using last version of nobara. is a fedora 37 with some improvements, like trying to make it easier to install nvidia. anyway... I did a new installation and chose NOT to install nvidia using the nobara automator. 

![image](https://user-images.githubusercontent.com/20627847/220409387-efb4ba11-78f7-4014-afe3-6758249f0852.png)
cheksu

![image](https://user-images.githubusercontent.com/20627847/220409469-3a342a26-d82a-4d42-9cf5-0db188f7aadd.png)
compat

![image](https://user-images.githubusercontent.com/20627847/220409572-2a7dcf6a-39ab-4981-ad98-735d011f363c.png)
rpmadd

![image](https://user-images.githubusercontent.com/20627847/220409720-3aafbf0f-e670-42d9-bcb4-269ec720cebd.png)
drive. missing xorg-x11-drv-nvidia xorg-x11-drv-nvidia-libs... and i did as per the https://github.com/t0xic0der/nvidia-auto-installer-for-fedora-linux/issues/160:
sudo dnf install https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
sudo dnf install xorg-x11-drv-nvidia xorg-x11-drv-nvidia-libs
and both packages appeared

![image](https://user-images.githubusercontent.com/20627847/220410612-e0514213-85eb-41a8-8933-ba3d72e928e7.png)
but now, appears this error message...

what can i do now?

**Comment by gridhead** [comment]
Hi @fabiopesaju,

I think that on Nobara Workstation, the automated installation of proprietary NVIDIA drivers is already taken care of with the use of the stated `nobara-nvidia-wizard`[1]. It is better to stick with the inbuilt solution for installing those drivers over using `nvautoinstall`.

@GloriousEggroll tagging you here - feel free to correct me if I am mistaken :)

Index

1. Noting from the line `nobara-nvidia-wizard-1.0.6.fc37.noarch` that was detected as a supposed driver package

**Comment by onuralpszr** [comment]
I am closing this issue for now, because it is been a while and no replies come.
