### ISSUE TITLE
Weird wayland graphic gui bug 

### ISSUE THREAD

**Issue by ryzendew** [t0xic0der/nvidia-auto-installer-for-fedora-linux#295]
![image](https://github.com/gridhead/nvidia-auto-installer-for-fedora-linux/assets/84041391/6b8aea17-d119-48b4-914a-c26b95f77dc5)
have you got a fix for this ?

**Comment by gridhead** [comment]
@RyzenDew Unfortunately the scope of this tool is limited to simply installing the drivers. I am afraid we might not be able to help you with this.
