### ISSUE TITLE
Documentation needs critical correction

### ISSUE THREAD

**Issue by gridhead** [t0xic0der/nvidia-auto-installer-for-fedora-linux#32]
There are certain information not provided correctly on the README.md.
- The binary is not executable from the get-go so requires a `chmod +x NVAutoInstFedora32` first
- The documentation does not state about root permission and how to obtain it

**Comment by Ank-22** [comment]
Can you assign this to me? I will study and update it

**Comment by gridhead** [comment]
Sure thing. :slightly_smiling_face:
