### ISSUE TITLE
Create builds for Fedora 41

### ISSUE THREAD

**Issue by sschuberth** [t0xic0der/nvidia-auto-installer-for-fedora-linux#330]
Looking at https://copr.fedorainfracloud.org/coprs/t0xic0der/nvidia-auto-installer-for-fedora/build/6627555/, the `fedora-41-x86_64` entry says "RPM build has not started yet", and following the link to [here](https://download.copr.fedorainfracloud.org/results/t0xic0der/nvidia-auto-installer-for-fedora/fedora-41-x86_64/06627555-nvautoinstall/) shows `*-fc40.*.rpm` file names, although it should probably be "41" instead of "40".

**Comment by gridhead** [comment]
Roger. Getting to it.

**Comment by gridhead** [comment]
@sschuberth the new releases are now available here https://copr.fedorainfracloud.org/coprs/t0xic0der/nvidia-auto-installer-for-fedora/build/8192842/.

Ref. https://github.com/gridhead/nvidia-auto-installer-for-fedora-linux/releases/tag/v0.4.2
