### ISSUE TITLE
Add CONTRIBUTING.md and CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by gridhead** [t0xic0der/nvidia-auto-installer-for-fedora-linux#52]
In the spirit of getting more contributors for the project, the above documents would be appreciated.

**Comment by codeperfectplus** [comment]
@t0xic0der I like to be assigned for the adding `CONTRIBUTING.md` docs.

**Comment by gridhead** [comment]
Thank you for considering the issue, @codePerfectPlus. If you are considering the issue, please consider it wholly and add CODE_OF_CONDUCT.md as well.

**Comment by codeperfectplus** [comment]
Yeah I will add CODE_OF_CONDUCT.md too.

**Comment by gridhead** [comment]
Cool. Thanks. :smile:

**Comment by gridhead** [comment]
Hi @codePerfectPlus, Be sure to get yourself registered at https://organize.mlh.io/participants/events/4659-hack-astrosonic, our official Hacktoberfest event to stay in touch with the fellow contributors of this project.

Also, feel free to leave a star on the project - should you find it worth your time. Happy hacking! :smile:

**Comment by gridhead** [comment]
Closing this issue as it was addressed with #53.
