### ISSUE TITLE
0.3.5

### ISSUE THREAD

**Issue by changemenemo** [t0xic0der/nvidia-auto-installer-for-fedora-linux#59]
You new release is an archive... not the usual script... So what do you want us to do with it? 
Thanks

**Comment by gridhead** [comment]
Hi @boistordu, the most recent release is now packaged and made generally available at COPR. 

Simply execute the following commands in succession to install the tool.

```shell
# dnf install dnf-plugins-core -y
# dnf copr enable t0xic0der/nvidia-auto-installer-for-fedora -y
# dnf install nvautoinstall -y
```

**Comment by changemenemo** [comment]
okey thanks for  that.
