### ISSUE TITLE
Nvidia driver not loading

### ISSUE THREAD

**Issue by DSeeLP** [t0xic0der/nvidia-auto-installer-for-fedora-linux#63]
I ran
```bash
sudo nvautoinstall --rpmadd
sudo nvautoinstall --nvrepo
sudo nvautoinstall --driver
```
And it said that the driver installed successfully. I restarted my system and found out that the nvidia drivers aren't loaded, instead the nouveau driver was loaded.

How can i fix this?
Im running Fedora 34.
My graphics card is a GTX970.

**Comment by DSeeLP** [comment]
Im using a fresh install of Fedora 34 with kernel 5.12.6

**Comment by HNGamingUK** [comment]
> Im using a fresh install of Fedora 34 with kernel 5.12.6

Did you ever work out what caused this? I am having the same issue and running 2060 Super.

**Comment by gridhead** [comment]
Could you please check if you have secure boot enabled?

**Comment by gridhead** [comment]
Also, I would suggest posting your questions at https://ask.fedoraproject.org/ as the issue is more related to the driver and not with the installer.
