### ISSUE TITLE
Error after installation - Nvidia kernel module missing

### ISSUE THREAD

**Issue by marifcelik** [t0xic0der/nvidia-auto-installer-for-fedora-linux#64]
installed without any problems, but I got this error on the boot. Nvidia app won't open. Im using Lenovo ideapad Gaming 3-15ARH05 Laptop - Amd Ryzen 7 4800H and Gtx1650ti.
screenshot: https://www.hizliresim.com/rzmzq4v

**Comment by Exordio** [comment]
same error

**Comment by gridhead** [comment]
Hey @arifcelik56 @Exordio,

Sincere apologies for the delayed reply. Could you please check if the secure boot is turned off or not?

**Comment by Exordio** [comment]
Yes, I have already solved my problem. After rebuilding the computer in the BIOS, for some reason, secure boot turned on. 
The funny thing is, I disabled it before and the driver worked fine. In general, what the hell did he turn on, I don't know xd.

**Comment by marifcelik** [comment]
Hi @t0xic0der .
Secure boot was off but I hadn't checked at the time. I deleted it to be able to use the computer but I will install it again soon. I'll post the result here.

**Comment by gridhead** [comment]
Closing this issue as fixed. For folks who come across a similar issue, try toggling the secure boot to see if it works.
