### ISSUE TITLE
laptop display still not working with kernel above 5.12

### ISSUE THREAD

**Issue by dicatalin** [t0xic0der/nvidia-auto-installer-for-fedora-linux#69]
I don't know if this is the right place but on Fedora 34 with kernel above 5.12, laptop display are still not working after installing the drivers. Funny thing is that an external monitor connected over hdmi is working.
HP ProBook 450 G7, I7-10510U CPU, Nvidia GeForce MX250 OS: Fedora release 34 (Thirty Four)

**Comment by gridhead** [comment]
Hey @dicatalin, I would request you to redirect your question to https://ask.fedoraproject.org/ as yours is more related to the actual driver and not the installer. Thanks for reaching out.
