### ISSUE TITLE
Fedora 34 - Incorrect Nvidia cuda repo

### ISSUE THREAD

**Issue by HNGamingUK** [t0xic0der/nvidia-auto-installer-for-fedora-linux#76]
It has been noted that for Fedora 34 the nvautoinstall tool actually adds the Nvidia cuda repo for Fedora 33....

I believe this should be fixed as there is a Fedora 34 repo. For the majority of users I can imagine this won't cause much of an issue, however it has been noted in the following rpmfusion bug report https://bugzilla.rpmfusion.org/show_bug.cgi?id=6105 that OBS will fail to work on Fedora34.

This is due to nsight-compute-2020 marking itself as having the library required but being in the incorrect location. nsight-compute-2020 is only part of the Fedora33 repo, nvidia have a -2021 version which doesn't mark it as having the file. 

Hope this makes sense, thanks!

**Comment by gridhead** [comment]
@HNGamingUK, thanks for bringing it to my attention.

I will promptly add the suggested repositories.
