### ISSUE TITLE
Fedora 35 KDE Plasma: RPM Fusion repository for Proprietary NVIDIA Driver was not found 

### ISSUE THREAD

**Issue by CleanHit** [t0xic0der/nvidia-auto-installer-for-fedora-linux#77]
I'm using Fedora 35 KDE Plasma on a Asus Zephyrus G14 laptop with GTX 1600 TI (Max-Q). I haven't been using Nvidia drivers on Linux so far and I'm trying this out for the first time using this repo. When I run `sudo nvautoinstall --rpmadd` I get:
```cmd
[ # ] NVIDIA AUTOINSTALLER FOR FEDORA
[ ★ ] CHECKING SUPERUSER PERMISSIONS...
[ ✓ ] Superuser privilege acquired
[ ★ ] CHECKING AVAILABILITY OF RPM FUSION NVIDIA REPOSITORY...
[ ✗ ] RPM Fusion repository for Proprietary NVIDIA Driver was not detected
[ ✗ ] Leaving installer
```
I do have `rpmfusion-nonfree` and `rpmfusion-free` packages installed

**Comment by gridhead** [comment]
Thanks for reporting. I'll investigate the issue and get back to you on this.

**Comment by CleanHit** [comment]
@t0xic0der thank you for fixing this issue and happy new year!
